FROM node:lts-alpine
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
COPY yarn.lock ./
RUN mkdir ./node_modules
RUN chown node:node ./node_modules
RUN yarn install
COPY . .
EXPOSE 8000
CMD npm install; npm start
