FROM node:lts-alpine

# Create directory for app
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json .
COPY yarn.lock .

RUN yarn install

# Add the rest of the app
COPY . .

EXPOSE 8000
CMD [ "yarn", "start" ]
