FROM node:lts-alpine
WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./

# Weird permissions fix (idk if it even works)
RUN mkdir ./node_modules
RUN chown node:node ./node_modules

RUN yarn install
COPY . .
EXPOSE 8000
CMD npm install; npm start
