# Pull the Node image from Docker Hub
FROM node:lts-alpine

# Setting Working Directory
WORKDIR /usr/src/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

EXPOSE 3000

# Run the API on Nodemon
CMD ["npm", "run", "start"]
